# Generated by Django 4.2.1 on 2023-05-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system_app', '0002_alter_employee_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
