# Generated by Django 4.2.1 on 2023-05-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_system_app', '0003_alter_sessionyearmodel_session_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session_year_id',
        ),
    ]
