# Generated by Django 4.2.1 on 2023-05-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system_app', '0004_remove_student_session_year_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
