# Generated by Django 4.2.1 on 2023-05-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_system_app', '0005_alter_student_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='student_id',
            new_name='ward',
        ),
    ]
